# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import c2_pb2 as c2__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in c2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class C2Stub(object):
    """
    Service

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClaimTasks = channel.unary_unary(
                '/c2.C2/ClaimTasks',
                request_serializer=c2__pb2.ClaimTasksRequest.SerializeToString,
                response_deserializer=c2__pb2.ClaimTasksResponse.FromString,
                _registered_method=True)
        self.FetchAsset = channel.unary_stream(
                '/c2.C2/FetchAsset',
                request_serializer=c2__pb2.FetchAssetRequest.SerializeToString,
                response_deserializer=c2__pb2.FetchAssetResponse.FromString,
                _registered_method=True)
        self.ReportCredential = channel.unary_unary(
                '/c2.C2/ReportCredential',
                request_serializer=c2__pb2.ReportCredentialRequest.SerializeToString,
                response_deserializer=c2__pb2.ReportCredentialResponse.FromString,
                _registered_method=True)
        self.ReportFile = channel.stream_unary(
                '/c2.C2/ReportFile',
                request_serializer=c2__pb2.ReportFileRequest.SerializeToString,
                response_deserializer=c2__pb2.ReportFileResponse.FromString,
                _registered_method=True)
        self.ReportProcessList = channel.unary_unary(
                '/c2.C2/ReportProcessList',
                request_serializer=c2__pb2.ReportProcessListRequest.SerializeToString,
                response_deserializer=c2__pb2.ReportProcessListResponse.FromString,
                _registered_method=True)
        self.ReportTaskOutput = channel.unary_unary(
                '/c2.C2/ReportTaskOutput',
                request_serializer=c2__pb2.ReportTaskOutputRequest.SerializeToString,
                response_deserializer=c2__pb2.ReportTaskOutputResponse.FromString,
                _registered_method=True)
        self.ReverseShell = channel.stream_stream(
                '/c2.C2/ReverseShell',
                request_serializer=c2__pb2.ReverseShellRequest.SerializeToString,
                response_deserializer=c2__pb2.ReverseShellResponse.FromString,
                _registered_method=True)
        self.CreatePortal = channel.stream_stream(
                '/c2.C2/CreatePortal',
                request_serializer=c2__pb2.CreatePortalRequest.SerializeToString,
                response_deserializer=c2__pb2.CreatePortalResponse.FromString,
                _registered_method=True)


class C2Servicer(object):
    """
    Service

    """

    def ClaimTasks(self, request, context):
        """
        Contact the server for new tasks to execute.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAsset(self, request, context):
        """
        Fetch an asset from the server, returning one or more chunks of data.
        The maximum size of these chunks is determined by the server.
        The server should reply with two headers:
        - "sha3-256-checksum": A SHA3-256 digest of the entire file contents.
        - "file-size": The number of bytes contained by the file.

        If no associated file can be found, a NotFound status error is returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCredential(self, request, context):
        """
        Report a credential from the host to the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFile(self, request_iterator, context):
        """
        Report a file from the host to the server.
        Providing content of the file is optional. If content is provided:
        - Hash will automatically be calculated and the provided hash will be ignored.
        - Size will automatically be calculated and the provided size will be ignored.

        Content is provided as chunks, the size of which are up to the agent to define (based on memory constraints).
        Any existing files at the provided path for the host are replaced.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProcessList(self, request, context):
        """
        Report the active list of running processes. This list will replace any previously reported
        lists for the same host.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskOutput(self, request, context):
        """
        Report execution output for a task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseShell(self, request_iterator, context):
        """
        Open a reverse shell bi-directional stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePortal(self, request_iterator, context):
        """
        Open a portal bi-directional stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_C2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClaimTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTasks,
                    request_deserializer=c2__pb2.ClaimTasksRequest.FromString,
                    response_serializer=c2__pb2.ClaimTasksResponse.SerializeToString,
            ),
            'FetchAsset': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchAsset,
                    request_deserializer=c2__pb2.FetchAssetRequest.FromString,
                    response_serializer=c2__pb2.FetchAssetResponse.SerializeToString,
            ),
            'ReportCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCredential,
                    request_deserializer=c2__pb2.ReportCredentialRequest.FromString,
                    response_serializer=c2__pb2.ReportCredentialResponse.SerializeToString,
            ),
            'ReportFile': grpc.stream_unary_rpc_method_handler(
                    servicer.ReportFile,
                    request_deserializer=c2__pb2.ReportFileRequest.FromString,
                    response_serializer=c2__pb2.ReportFileResponse.SerializeToString,
            ),
            'ReportProcessList': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProcessList,
                    request_deserializer=c2__pb2.ReportProcessListRequest.FromString,
                    response_serializer=c2__pb2.ReportProcessListResponse.SerializeToString,
            ),
            'ReportTaskOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskOutput,
                    request_deserializer=c2__pb2.ReportTaskOutputRequest.FromString,
                    response_serializer=c2__pb2.ReportTaskOutputResponse.SerializeToString,
            ),
            'ReverseShell': grpc.stream_stream_rpc_method_handler(
                    servicer.ReverseShell,
                    request_deserializer=c2__pb2.ReverseShellRequest.FromString,
                    response_serializer=c2__pb2.ReverseShellResponse.SerializeToString,
            ),
            'CreatePortal': grpc.stream_stream_rpc_method_handler(
                    servicer.CreatePortal,
                    request_deserializer=c2__pb2.CreatePortalRequest.FromString,
                    response_serializer=c2__pb2.CreatePortalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'c2.C2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('c2.C2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class C2(object):
    """
    Service

    """

    @staticmethod
    def ClaimTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2.C2/ClaimTasks',
            c2__pb2.ClaimTasksRequest.SerializeToString,
            c2__pb2.ClaimTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/c2.C2/FetchAsset',
            c2__pb2.FetchAssetRequest.SerializeToString,
            c2__pb2.FetchAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2.C2/ReportCredential',
            c2__pb2.ReportCredentialRequest.SerializeToString,
            c2__pb2.ReportCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/c2.C2/ReportFile',
            c2__pb2.ReportFileRequest.SerializeToString,
            c2__pb2.ReportFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportProcessList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2.C2/ReportProcessList',
            c2__pb2.ReportProcessListRequest.SerializeToString,
            c2__pb2.ReportProcessListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTaskOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2.C2/ReportTaskOutput',
            c2__pb2.ReportTaskOutputRequest.SerializeToString,
            c2__pb2.ReportTaskOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReverseShell(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/c2.C2/ReverseShell',
            c2__pb2.ReverseShellRequest.SerializeToString,
            c2__pb2.ReverseShellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePortal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/c2.C2/CreatePortal',
            c2__pb2.CreatePortalRequest.SerializeToString,
            c2__pb2.CreatePortalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
