# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dns.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dns.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdns.proto\x12\x03\x64ns\"\xb3\x01\n\tDNSPacket\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.dns.PacketType\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x17\n\x0f\x63onversation_id\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\r\n\x05\x63rc32\x18\x05 \x01(\r\x12\x13\n\x0bwindow_size\x18\x06 \x01(\r\x12\x1b\n\x04\x61\x63ks\x18\x07 \x03(\x0b\x32\r.dns.AckRange\x12\r\n\x05nacks\x18\x08 \x03(\r\".\n\x08\x41\x63kRange\x12\x11\n\tstart_seq\x18\x01 \x01(\r\x12\x0f\n\x07\x65nd_seq\x18\x02 \x01(\r\"_\n\x0bInitPayload\x12\x13\n\x0bmethod_code\x18\x01 \x01(\t\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\r\x12\x12\n\ndata_crc32\x18\x03 \x01(\r\x12\x11\n\tfile_size\x18\x04 \x01(\r\"#\n\x0c\x46\x65tchPayload\x12\x13\n\x0b\x63hunk_index\x18\x01 \x01(\r\"P\n\x10ResponseMetadata\x12\x14\n\x0ctotal_chunks\x18\x01 \x01(\r\x12\x12\n\ndata_crc32\x18\x02 \x01(\r\x12\x12\n\nchunk_size\x18\x03 \x01(\r*\x84\x01\n\nPacketType\x12\x1b\n\x17PACKET_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10PACKET_TYPE_INIT\x10\x01\x12\x14\n\x10PACKET_TYPE_DATA\x10\x02\x12\x15\n\x11PACKET_TYPE_FETCH\x10\x03\x12\x16\n\x12PACKET_TYPE_STATUS\x10\x04\x42$Z\"realm.pub/tavern/internal/c2/dnspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dns_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"realm.pub/tavern/internal/c2/dnspb'
  _globals['_PACKETTYPE']._serialized_start=465
  _globals['_PACKETTYPE']._serialized_end=597
  _globals['_DNSPACKET']._serialized_start=19
  _globals['_DNSPACKET']._serialized_end=198
  _globals['_ACKRANGE']._serialized_start=200
  _globals['_ACKRANGE']._serialized_end=246
  _globals['_INITPAYLOAD']._serialized_start=248
  _globals['_INITPAYLOAD']._serialized_end=343
  _globals['_FETCHPAYLOAD']._serialized_start=345
  _globals['_FETCHPAYLOAD']._serialized_end=380
  _globals['_RESPONSEMETADATA']._serialized_start=382
  _globals['_RESPONSEMETADATA']._serialized_end=462
# @@protoc_insertion_point(module_scope)
