# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: portal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'portal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cportal.proto\x12\x06portal\"D\n\x0c\x42ytesPayload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12&\n\x04kind\x18\x02 \x01(\x0e\x32\x18.portal.BytesPayloadKind\">\n\nTCPPayload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x64st_addr\x18\x02 \x01(\t\x12\x10\n\x08\x64st_port\x18\x03 \x01(\r\">\n\nUDPPayload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x64st_addr\x18\x02 \x01(\t\x12\x10\n\x08\x64st_port\x18\x03 \x01(\r\"\xa1\x01\n\x04Mote\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x0e\n\x06seq_id\x18\x02 \x01(\x04\x12!\n\x03udp\x18\x03 \x01(\x0b\x32\x12.portal.UDPPayloadH\x00\x12!\n\x03tcp\x18\x04 \x01(\x0b\x32\x12.portal.TCPPayloadH\x00\x12%\n\x05\x62ytes\x18\x05 \x01(\x0b\x32\x14.portal.BytesPayloadH\x00\x42\t\n\x07payload\"B\n\x11OpenPortalRequest\x12\x11\n\tportal_id\x18\x01 \x01(\x03\x12\x1a\n\x04mote\x18\x02 \x01(\x0b\x32\x0c.portal.Mote\"0\n\x12OpenPortalResponse\x12\x1a\n\x04mote\x18\x02 \x01(\x0b\x32\x0c.portal.Mote*\xce\x01\n\x10\x42ytesPayloadKind\x12\"\n\x1e\x42YTES_PAYLOAD_KIND_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x42YTES_PAYLOAD_KIND_DATA\x10\x01\x12\x1b\n\x17\x42YTES_PAYLOAD_KIND_PING\x10\x02\x12 \n\x1c\x42YTES_PAYLOAD_KIND_KEEPALIVE\x10\x03\x12\x1c\n\x18\x42YTES_PAYLOAD_KIND_TRACE\x10\x04\x12\x1c\n\x18\x42YTES_PAYLOAD_KIND_CLOSE\x10\x05\x32S\n\x06Portal\x12I\n\nOpenPortal\x12\x19.portal.OpenPortalRequest\x1a\x1a.portal.OpenPortalResponse\"\x00(\x01\x30\x01\x42#Z!realm.pub/tavern/portals/portalpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!realm.pub/tavern/portals/portalpb'
  _globals['_BYTESPAYLOADKIND']._serialized_start=505
  _globals['_BYTESPAYLOADKIND']._serialized_end=711
  _globals['_BYTESPAYLOAD']._serialized_start=24
  _globals['_BYTESPAYLOAD']._serialized_end=92
  _globals['_TCPPAYLOAD']._serialized_start=94
  _globals['_TCPPAYLOAD']._serialized_end=156
  _globals['_UDPPAYLOAD']._serialized_start=158
  _globals['_UDPPAYLOAD']._serialized_end=220
  _globals['_MOTE']._serialized_start=223
  _globals['_MOTE']._serialized_end=384
  _globals['_OPENPORTALREQUEST']._serialized_start=386
  _globals['_OPENPORTALREQUEST']._serialized_end=452
  _globals['_OPENPORTALRESPONSE']._serialized_start=454
  _globals['_OPENPORTALRESPONSE']._serialized_end=502
  _globals['_PORTAL']._serialized_start=713
  _globals['_PORTAL']._serialized_end=796
# @@protoc_insertion_point(module_scope)
