apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ccdc-readonly-bins
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*" # Apply to all hosts
  file:
    matchDirectories:
      - dir: /bin
        recursive: true
        readOnly: true
      - dir: /sbin
        recursive: true
        readOnly: true
      - dir: /usr/bin
        recursive: true
        readOnly: true
      - dir: /usr/sbin
        recursive: true
        readOnly: true
  action:
    Block