apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ccdc-readonly-web
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*" # Apply to all hosts
  file:
    matchDirectories:
      dir: /var/www/ # try sleep 1
      recursive: true
      readOnly: true
  action:
    Block
