apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ccdc-process-block
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*" # Apply to all hosts
  process:
    matchDirectories:
    - dir: /home
      recursive: true
    - dir: /root
      recursive: true
    - dir: /tmp
      recursive: true
    - dir: /dev/shm
      recursive: true
    - dir: /var/log
      recursive: true
  action:
    Block
